version: '3.8'
services:
  cadvisor-aio:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-aio
    hostname: cadvisor-aio
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 2710:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
  
  grafana-aio:
    image: grafana/grafana-enterprise:latest
    container_name: grafana-aio
    hostname: grafana-aio
    restart: unless-stopped
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    networks:
      - proxy
    ports:
    - 2720:3000
    volumes:
    - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    - ./grafana-data:/var/lib/grafana


  loki-aio:
    image: grafana/loki:latest #2.3.0
    container_name: loki-aio
    hostname: loki-aio
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - proxy
    ports:
    - 2730:3100
    volumes:
    - ./config/loki-config-s3.yml:/etc/loki/loki-config.yml:ro
    - ./loki-data:/tmp/loki


  node-exporter-aio:
    image: prom/node-exporter:latest
    container_name: node-exporter-aio
    hostname: node-exporter-aio
    restart: unless-stopped
    command: --path.rootfs=/host
    networks:
      - proxy
    pid: host
    ports:
    - 2740:9100
    volumes:
    - /:/host:ro,rslave

  prometheus-aio:
    container_name: prometheus-aio
    hostname: prometheus-aio
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-admin-api
    - --web.enable-lifecycle
    networks:
      - proxy
    ports:
    - 2750:9090
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./prometheus-data:/prometheus

  promtail-aio:
    container_name: promtail-aio
    hostname: promtail-aio
    image: grafana/promtail:latest #2.3.0
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    networks:
      - proxy
    ports:
    - 1514:1514
    - 2760:9080
    volumes:
    - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml:ro

  syslog-ng-aio:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng-aio
    hostname: syslog-ng-aio
    restart: unless-stopped
    command: -edv
    depends_on:
    - promtail-aio
    networks:
      - proxy
    ports:
    - 514:514/udp
    - 601:601
    volumes:
    - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro

networks:
  proxy:
    external: true
